name: Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.yml'
      - '!.github/workflows/release.yml'

jobs:
  release-plz:
    name: Release-plz
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
          token: ${{ secrets.OXC_BOT_PAT }}

      - uses: Boshen/setup-rust@main

      - uses: MarcoIeni/release-plz-action@269387141c39d8ba9eed025ab109e462ada263f2 # v0.5
        env:
          GITHUB_TOKEN: ${{ secrets.OXC_BOT_PAT }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
